import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Khi nào có header thì xóa cái này */}
        <div className="flex justify-center items-center w-full h-48 bg-gray-100 border-b border-gray-300">
          <h1 className="text-3xl font-bold">Header</h1>
        </div>
        {children}
        {/* Khi nào có footer thì xóa cái này */}
        <div className="flex justify-center items-center w-full h-48 bg-black border-t border-gray-300">
          <h1 className="text-white text-3xl font-bold">Footer</h1>
        </div>
      </body>
    </html>
  );
}
