import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import logo from "../../public/logo.png";
import Image from 'next/image';
import search from '../../public/search.svg';
import Cart from '../../public/cart.svg';
import User from '../../public/user.png'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <div id="navbar" className="flex justify-evenly items-end p-5 bg-(--background) border-b-2 border-(--tertiary) h-[125px]">
      <Image src={logo} alt="logo" width={60} height={61}/>
      <h1 className="text-2xl font-bold">Shop của bạn</h1>
      <form className="border-2 w-293/720 flex align-middle rounded-xl">
        <button id="search" className="w-42/500 h-[42px] p-3">
          <Image src={search} alt="Search icon" />
        </button>
        <input type="search" placeholder="Search ..." className="w-full h-[42px] p-4 border-none"></input>
      </form>
      <Image src={Cart} alt="Cart" width={38} height={34} />
      <Image src={User} alt="User" width={38} height={34} />
    </div>
    
  )
}

function Footer() {
  return (
    <div>

    </div>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
