import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css";
import logo from "../../public/logo.png";
import Image from 'next/image';
import search from '../../public/search.svg';
import Cart from '../../public/cart.svg';
// import User from '../../public/user.png';
import Header from '@/app/_comhome/Header';
import Link from "next/link";

import Navbar from "./Navbar";
import Footer from "./Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased}`}
      >
        {/* Khi nào có header thì xóa cái này */}
        <Navbar />
        {children}
        {/* Khi nào có footer thì xóa cái này */}
        <Footer />
      </body>
    </html>
  );
}